eda
unimet-psicologia/Tesis_AdiccionRedesSociales-Ansiedad-Autoestima-ImagenCorporal pull request #5
Opened 2022-10-04 17:24 UTC by Francesco2709

2022-10-06 16:23 UTC, dieko95 requested changes
Tienen que cambiar: 

- [ ] Histogramas a gráficos de barras siguiendo el código que subí de la variable `Municipios`. 
- [ ] Utilizar `BetweenStats` en lugar de gráficos de violin. Cambiar si es parametrico o no según los resultados de los supuestos. Pueden encontrar el código en uno de los últimos comentarios del PR. 
- [ ] Otros cambios que pueden ver en los comentarios del PR.

2022-10-06 16:23 UTC, dieko95 commented on notebooks/1.0_francesco_juan_analisis_data_exploratorio.Rmd
> +
@Francesco2709 Te recomiendo escribir acá los resultados de total encuestados y porcentajes. Por ejemplo, de tantos encuestados, X% no fueron incluidos por no residir en el Área Metropolitana de Caracas, etc....

2022-10-06 16:23 UTC, dieko95 commented on notebooks/1.0_francesco_juan_analisis_data_exploratorio.Rmd
> +    sum()
@Francesco2709 borra estas líneas, solo vamos a usar `vis_miss`

2022-10-06 16:23 UTC, dieko95 commented on notebooks/1.0_francesco_juan_analisis_data_exploratorio.Rmd
> +  View(original_df)
@Francesco2709 Borra línea, no es necesario ver el dataframe acá.

2022-10-06 16:23 UTC, dieko95 commented on notebooks/1.0_francesco_juan_analisis_data_exploratorio.Rmd
> +#outlyiers de factores adiccion a las redes sociales
Typo. Cambia Outlyiers -> Outliers

2022-10-06 16:23 UTC, dieko95 commented on notebooks/1.0_francesco_juan_analisis_data_exploratorio.Rmd
> +
@Francesco2709 coloca qué has visto sobre los outliers en el texto. Esto puede ayudar a ir puliendo el análisis de los resultados.

2022-10-06 16:23 UTC, dieko95 commented on notebooks/1.0_francesco_juan_analisis_data_exploratorio.Rmd
> +#outlyiers de factores Autoestima
Typo

2022-10-06 16:23 UTC, dieko95 commented on notebooks/1.0_francesco_juan_analisis_data_exploratorio.Rmd
> +
Colocar analisis de resultados en texto.

2022-10-06 16:23 UTC, dieko95 commented on notebooks/1.0_francesco_juan_analisis_data_exploratorio.Rmd
> +#outlyiers de factores BSQ
Typo

2022-10-06 16:23 UTC, dieko95 commented on notebooks/1.0_francesco_juan_analisis_data_exploratorio.Rmd
> +
Escribir analisis de resultados. Siéntete libre de añadir por qué hay outliers en este instrumento.

2022-10-06 16:23 UTC, dieko95 commented on notebooks/1.0_francesco_juan_analisis_data_exploratorio.Rmd
> +    geom_histogram(binwidth = 0.5, stat = "count", colour = "black", linetype = 1) +
@Francesco2709 no es correcto utilizar un histograma para esta variable. Recuerda que es una variable categórica, tenemos que utilizar un gráfico de barras.

2022-10-06 16:23 UTC, dieko95 commented on notebooks/1.0_francesco_juan_analisis_data_exploratorio.Rmd
> +              size = 3)
@Francesco2709 he colocado acá un ejemplo de cómo hacer los gráficos de barra con porcentaje. Igualmente estabas utilizando un histograma para visualizar una variable categórica. Acá debes utilizar un gráfico de barras (`geom_col`). 

Para añadir los porcentajes tienes que hacer lo siguiente: 
Ccontar la cantidad de sujetos por municipios, luego calcular porcentajes. Ese dataframe lo usas como input en ggplot.

2022-10-06 16:23 UTC, dieko95 commented on notebooks/1.0_francesco_juan_analisis_data_exploratorio.Rmd
> +chisq.test(table(original_df$municipio))
Elimina estas líneas, vamos a utilizar el chi cuadrado de google sheets.

2022-10-06 16:23 UTC, dieko95 commented on notebooks/1.0_francesco_juan_analisis_data_exploratorio.Rmd
> +original_df%>%
Reutilizar solución que te di para municipios.

2022-10-06 16:23 UTC, dieko95 commented on notebooks/1.0_francesco_juan_analisis_data_exploratorio.Rmd
> +
Eliminar, vamos a utilizar los de google sheets.

2022-10-06 16:23 UTC, dieko95 commented on notebooks/1.0_francesco_juan_analisis_data_exploratorio.Rmd
> +```
Reutilizar gráfico de municipio

2022-10-06 16:23 UTC, dieko95 commented on notebooks/1.0_francesco_juan_analisis_data_exploratorio.Rmd
> +```
Reutilizar gráfico de municipio

2022-10-06 16:23 UTC, dieko95 commented on notebooks/1.0_francesco_juan_analisis_data_exploratorio.Rmd
> +  original_df[is.na(original_df)] <- "no valido"
Elimina esto. Nosotros queremos tener `NA` en estos datos porque los sujetos no respondieron. Reemplazarlos con otro valor no aporta al análisis.

2022-10-06 16:23 UTC, dieko95 commented on notebooks/1.0_francesco_juan_analisis_data_exploratorio.Rmd
> +  #aes(x= "Ocupacion", y= "Factor 1 Redes Sociales")
@dieko95 Cambiar todos los Violin plots por:

```
# Igualdad de varianzas: si p > 0.05 supuesto se cumple
LeveneTest(original_df$fac1_ars, original_df$trabajo_actual)

# Normalidad de VD: si p > 0.05 supuesto se cumple
shapiro.test(original_df$fac1_ars)

ggbetweenstats(
  data  = original_df,
  x     = trabajo_actual,
  y     = fac1_ars,
  outlier.tagging  = TRUE,
  type = "nonparametric", # cambiar a "parametric" si supuestos se cumplen.
  title = "Factor 1 ARS Según Trabajo Actual" # Titulo con variables.
)
```

Recuerda instalar la libreria `ggstatsplot` y anadir las siguientes librerias al notebook: 
```
library(ggstatplot)
library(DescTools)
```

2022-10-06 16:23 UTC, dieko95 commented on notebooks/1.0_francesco_juan_analisis_data_exploratorio.Rmd
> +  geom_histogram(binwidth = 0.5, stat = "count", colour = "black", linetype = 1) +
Cambiar histograma a grafico de barras igual que municipio.

2022-10-06 16:23 UTC, dieko95 commented on notebooks/1.0_francesco_juan_analisis_data_exploratorio.Rmd
> +  geom_histogram(binwidth = 0.5, stat = "count", colour = "black", linetype = 1) +
cambiar a grafico de barras.

2022-10-06 23:29 UTC, Francesco2709 commented on notebooks/1.0_francesco_juan_analisis_data_exploratorio.Rmd
> +    sum()
ready

2022-10-06 23:30 UTC, Francesco2709 commented on notebooks/1.0_francesco_juan_analisis_data_exploratorio.Rmd
> +
no hay una forma de presentar estos datos en un cuadro mas bonito? asumo que tendré que que realizar una matriz

2022-10-06 23:34 UTC, Francesco2709 commented on notebooks/1.0_francesco_juan_analisis_data_exploratorio.Rmd
> +              size = 3)
gracias profe, super cool el dato

2022-10-22 21:07 UTC, dieko95 requested changes

2022-10-22 21:07 UTC, dieko95 commented on notebooks/1.0_francesco_juan_analisis_data_exploratorio.Rmd
> +```
@Francesco2709 Elimina estas lineas. Aún no vamos a hacer esto.

2022-10-22 21:07 UTC, dieko95 commented on notebooks/1.0_francesco_juan_analisis_data_exploratorio.Rmd
> +original_df <- mutate(original_df, factor_total_ars = original_df$fac1_ars + original_df$fac2_ars + original_df$fac3_ars)
@Francesco2709 no es necesario usar el `$` para acceder la columna. Mutate se utiliza sin `$`:  `mutate(original_df, factor_total_ars = fac1_ars + fac2_ars + fac3_ars)`

2022-10-22 21:07 UTC, dieko95 commented on notebooks/1.0_francesco_juan_analisis_data_exploratorio.Rmd
> +
@Francesco2709 esto es incorrecto, tenemos que utilizar correlación de pearson o spearman según las variables sean normales. 


Creé esta función para que se les sea más fácil hacer el análisis bivariante entre variables cuantitativas. 

Copia y pega este código al comienzo del notebook: 
```
run_quantitative_bivariate_test <-
  function(x_vector,
           y_vector,
           x_label = "",
           y_label = "",
           title = "") {
    x_vector_pvalue <- shapiro.test(x_vector)
    y_vector_pvalue <- shapiro.test(y_vector)
    
    if (y_vector_pvalue$p.value < 0.05) {
      method <- "pearson"
    } else {
      method <- "spearman"
    }
    
    
    cor_test_result <-
      cor.test(original_df$factor_total_ars,
               original_df$area_interperso,
               method = method)
    
    
    print(x_vector_pvalue)
    print(y_vector_pvalue)
    
    original_df %>%
      ggplot(aes(x = area_interperso, y = factor_total_ars)) +
      geom_point() +
      labs(x = x_label, y = y_label, title =
             title)
    
  }
```

Para hacer el análisis bivariante entre variables cuantitativas se utilizaría así: 

```
run_quantitative_bivariate_test(
  x_vector = original_df$area_interperso,
  y_vector = original_df$factor_total_ars,
  x_label = "Puntaje Autoestima Factor Area Interpersonal",
  y_label = "Puntaje Total Constructo Adicción a las Redes Sociales",
  title = "Relación entre Puntaje Total Constructo Adicción a las Redes Sociales y Factor Area Interpersonal"
)
```

2022-11-19 21:27 UTC, dieko95 approved these changes

2022-11-20 22:06 UTC, merged